# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 947295138e68d895835b1437b9849a3895d581ef354b0c71f56de24e7ba7a2f755d767a9de2e66d60bd2156a1b1ef30525cbab9aa4a166cbe9738fda7f498be2

test:
  secret_key_base: 2dffc9d10f60c266f7d74d9ac0357a73a756ba81ea0c9bd6aaae0efeefc468168c46a9421410bd3a08b2aeb2a4d0b2ef45c9fe847776925e8f6a493f779345f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
